"use client";

import {FormEvent,ReactNode,useCallback,useEffect,useState} from "react";
import {api,ApiError,qs,setCsrf,signIn,signOut,verifyMfa} from "../lib/api";

type Tab="dashboard"|"tenants"|"queues"|"automation"|"health"|"audit"|"plans"|"flags"|"security";
const tabs:Array<[Tab,string,string]>=[["dashboard","Platform Dashboard","⌂"],["tenants","Customers / Tenants","◎"],["queues","Queues / Jobs","⇄"],["automation","Automation / n8n","↗"],["health","Infrastructure Health","◇"],["audit","Audit / Security","▤"],["plans","Plans / Limits","▦"],["flags","Feature Flags","⚑"],["security","Admin Security","⚿"]];
function Badge({children,tone="neutral"}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Card({label,value,note}:{label:string;value:ReactNode;note?:string}){return <div className="card"><span>{label}</span><b>{value}</b>{note&&<small>{note}</small>}</div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-bg" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><h3>{title}</h3><button onClick={onClose}>×</button></header>{children}</div></div>}
function fmt(v:unknown){return new Intl.NumberFormat().format(Number(v||0))} function date(v:any){return v?new Date(v).toLocaleString():"—"}

function Login({done}:{done:()=>void}){
 const [email,setEmail]=useState("");const[password,setPassword]=useState("");const[challenge,setChallenge]=useState("");const[code,setCode]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await signIn(email,password);if(r.mfaRequired){setChallenge(r.challengeToken);return}if(!r.user?.platformAdmin)throw new Error("This account is not a platform administrator.");done()}catch(e){setError(e instanceof Error?e.message:"Sign in failed")}finally{setBusy(false)}}
 async function mfa(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await verifyMfa(challenge,code);done()}catch(e){setError(e instanceof Error?e.message:"MFA failed")}finally{setBusy(false)}}
 return <main className="login-page"><div className="login-box"><div className="admin-mark">A</div><h1>Super Admin</h1><p>Platform operations, tenant support, automation health and security controls.</p>{!challenge?<form onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="alert bad">{error}</div>}<button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form>:<form onSubmit={mfa}><div className="alert info">Password verified. Enter your authenticator code or a recovery code.</div><label>MFA code<input autoFocus required value={code} onChange={e=>setCode(e.target.value)} placeholder="000000"/></label>{error&&<div className="alert bad">{error}</div>}<button className="primary" disabled={busy}>{busy?"Verifying…":"Verify MFA"}</button></form>}</div></main>
}

export default function AdminApp(){
 const [me,setMe]=useState<any>(null);const[loading,setLoading]=useState(true);const[tab,setTab]=useState<Tab>("dashboard");const[error,setError]=useState("");
 const loadMe=useCallback(async()=>{setLoading(true);try{const r=await api<any>("/v1/auth/me");if(!r.principal?.platformAdmin)throw new Error("not admin");setMe(r.principal)}catch{setMe(null)}finally{setLoading(false)}},[]);useEffect(()=>{loadMe()},[loadMe]);
 if(loading)return <div className="center">Loading admin console…</div>;if(!me)return <Login done={loadMe}/>;
 async function logout(){await signOut();setMe(null)}
 return <div className="shell"><aside><div className="brand"><div className="admin-mark mini">A</div><div><b>Automation</b><span>Super Admin</span></div></div><nav>{tabs.map(([k,l,i])=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k)}><span>{i}</span>{l}</button>)}</nav><div className="aside-bottom"><small>{me.email}</small><button onClick={logout}>Sign out</button></div></aside><main><header className="top"><div><small>Platform operator</small><h1>{tabs.find(([k])=>k===tab)?.[1]}</h1></div><Badge tone={me.mfaVerifiedAt?"good":"warn"}>{me.mfaVerifiedAt?"MFA verified":"MFA setup / verification required"}</Badge></header>{error&&<div className="alert bad content-alert">{error}<button onClick={()=>setError("")}>×</button></div>}<section className="content">{tab==="dashboard"&&<Dashboard/>}{tab==="tenants"&&<Tenants/>}{tab==="queues"&&<Queues/>}{tab==="automation"&&<Automation/>}{tab==="health"&&<Health/>}{tab==="audit"&&<Audit/>}{tab==="plans"&&<Plans/>}{tab==="flags"&&<FeatureFlags/>}{tab==="security"&&<Security me={me} reload={loadMe}/>}</section></main></div>
}

function Dashboard(){const[d,setD]=useState<any>(null);useEffect(()=>{api("/v1/admin/dashboard").then(setD)},[]);if(!d)return <div className="center inner">Loading…</div>;const u=Object.fromEntries((d.usage24h||[]).map((r:any)=>[r.event_type,r]));return <><div className="cards"><Card label="Active tenants" value={fmt(d.tenants?.active)} note={`${fmt(d.tenants?.suspended)} suspended`}/><Card label="Open conversations" value={fmt(d.conversations?.open)} note={`${fmt(d.conversations?.human)} human mode`}/><Card label="Inbound / 24h" value={fmt(u.inbound_message?.quantity)}/><Card label="Outbound / 24h" value={fmt(u.outbound_message?.quantity)}/><Card label="AI calls / 24h" value={fmt(u.ai_call?.quantity)} note={`$${Number(u.ai_call?.estimated_cost||0).toFixed(4)} est.`}/><Card label="Orders / Bookings" value={`${fmt(d.outcomes24h?.orders)} / ${fmt(d.outcomes24h?.bookings)}`}/></div><div className="panel"><h3>Channel health</h3><div className="channel-grid">{(d.channels||[]).map((c:any)=><div key={c.platform}><b>{c.platform}</b><span>{c.connected} connected</span><small>{c.unhealthy} unhealthy · {c.total} total</small></div>)}</div></div></>}

function Tenants(){const[rows,setRows]=useState<any[]>([]);const[q,setQ]=useState("");const[selected,setSelected]=useState<any>(null);const load=useCallback(()=>api<any>(`/v1/admin/tenants${qs({q})}`).then(d=>setRows(d.tenants||[])),[q]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);async function open(id:string){setSelected(await api(`/v1/admin/tenants/${id}`))}async function toggle(){const t=selected.tenant;await api(`/v1/admin/tenants/${t.id}`,{method:"PATCH",body:JSON.stringify({status:t.status==="active"?"suspended":"active",reason:"Super Admin action"})});await open(t.id);load()}
 return <><div className="section-head"><div><h2>Tenants</h2><p>Cross-tenant visibility without exposing secrets. Support access is controlled and audited.</p></div><input className="search" placeholder="Search tenants…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="table"><table><thead><tr><th>Tenant</th><th>Status</th><th>Plan</th><th>Businesses</th><th>Channels</th><th>Created</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} onClick={()=>open(t.id)}><td><b>{t.name}</b><small>{t.slug}</small></td><td><Badge tone={t.status==="active"?"good":"warn"}>{t.status}</Badge></td><td>{t.plan_name||"—"}</td><td>{t.business_count}</td><td>{t.channel_count}</td><td>{date(t.created_at)}</td></tr>)}</tbody></table></div>{selected&&<Modal title={selected.tenant.name} onClose={()=>setSelected(null)}><div className="detail"><div><span>Status</span><Badge tone={selected.tenant.status==="active"?"good":"warn"}>{selected.tenant.status}</Badge></div><div><span>Plan</span><b>{selected.tenant.plan_name||"—"}</b></div><div><span>Members</span><b>{selected.members.length}</b></div><div><span>Businesses</span><b>{selected.businesses.length}</b></div><div><span>Channels</span><b>{selected.channels.length}</b></div></div><button className={selected.tenant.status==="active"?"danger":"primary"} onClick={toggle}>{selected.tenant.status==="active"?"Suspend tenant":"Reactivate tenant"}</button><h4>Channels</h4>{selected.channels.map((c:any)=><div className="list" key={c.id}><div><b>{c.name}</b><span>{c.platform} · {c.external_account_id}</span></div><Badge tone={c.connection_status==="connected"&&c.active?"good":"warn"}>{c.connection_status}</Badge></div>)}</Modal>}</>}

function Queues(){
 const[d,setD]=useState<any>(null);const[selected,setSelected]=useState<string>("");const[jobs,setJobs]=useState<any[]>([]);const[busy,setBusy]=useState("");
 const load=()=>api<any>("/v1/admin/queues").then(setD);
 const loadJobs=async(name:string)=>{setSelected(name);const r=await api<any>(`/v1/admin/queues/${encodeURIComponent(name)}/jobs?state=failed&limit=100`);setJobs(r.jobs||[])};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 async function retry(jobId:string){setBusy(jobId);try{await api(`/v1/admin/queues/${encodeURIComponent(selected)}/jobs/${encodeURIComponent(jobId)}/retry`,{method:"POST",body:"{}"});await loadJobs(selected);await load()}finally{setBusy("")}}
 async function remove(jobId:string){if(!confirm("Remove this failed job from the queue?"))return;setBusy(jobId);try{await api(`/v1/admin/queues/${encodeURIComponent(selected)}/jobs/${encodeURIComponent(jobId)}`,{method:"DELETE"});await loadJobs(selected);await load()}finally{setBusy("")}}
 async function toggle(name:string,paused:boolean){await api(`/v1/admin/queues/${encodeURIComponent(name)}/${paused?"resume":"pause"}`,{method:"POST",body:"{}"});await load()}
 return <><div className="section-head"><div><h2>Queue operations</h2><p>Waiting, active, delayed and dead-letter jobs across application-owned queues.</p></div><button onClick={load}>Refresh</button></div><div className="queue-grid">{d?.queues?.map((q:any)=><div className="panel" key={q.name}><div className="row"><h3>{q.name}</h3><Badge tone={q.counts.failed?"bad":q.isPaused?"warn":"good"}>{q.counts.failed?`${q.counts.failed} failed`:q.isPaused?"paused":"healthy"}</Badge></div><div className="mini"><div><b>{q.counts.waiting||0}</b><span>Waiting</span></div><div><b>{q.counts.active||0}</b><span>Active</span></div><div><b>{q.counts.delayed||0}</b><span>Delayed</span></div></div><small>Oldest wait: {q.oldestWaitingTimestamp?date(q.oldestWaitingTimestamp):"none"}</small><div className="row top-gap"><button onClick={()=>toggle(q.name,Boolean(q.isPaused))}>{q.isPaused?"Resume":"Pause"}</button>{q.counts.failed>0&&<button className="danger" onClick={()=>loadJobs(q.name)}>Inspect failed</button>}</div></div>)}</div>{selected&&<Modal title={`Failed jobs · ${selected}`} onClose={()=>{setSelected("");setJobs([])}}>{jobs.length?jobs.map(j=><div className="list" key={j.id}><div className="grow"><b>{j.name}</b><span>{j.id} · attempts {j.attemptsMade}</span><small>{j.failedReason||"No failure reason"}</small></div><div className="row"><button disabled={busy===j.id} onClick={()=>retry(j.id)}>Retry</button><button className="danger" disabled={busy===j.id} onClick={()=>remove(j.id)}>Remove</button></div></div>):<p>No failed jobs remain in this queue.</p>}</Modal>}</>
}
function Automation(){
 const[d,setD]=useState<any>(null);const load=()=>api<any>("/v1/admin/automation").then(setD);useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 return <><div className="section-head"><div><h2>Automation runtime</h2><p>Expected n8n bundle, runtime heartbeat, durable outbox and follow-up scheduling health.</p></div><button onClick={load}>Refresh</button></div>{!d?<div className="center inner">Loading…</div>:<><div className="cards"><Card label="Expected bundle" value={d.expectedBundleVersion||"—"}/><Card label="Runtime heartbeats" value={fmt(d.heartbeats?.length)}/><Card label="Deployments" value={fmt(d.deployments?.length)}/><Card label="Workers" value={fmt(d.workers?.length)}/></div><div className="panel"><h3>n8n runtime heartbeats</h3>{(d.heartbeats||[]).map((h:any)=><div className="list" key={h.runtime_key}><div><b>{h.runtime_key}</b><span>bundle {h.bundle_version} · API contract {h.api_contract_version}</span></div><Badge tone={Date.now()-new Date(h.last_seen_at).getTime()<180000?"good":"bad"}>{date(h.last_seen_at)}</Badge></div>)}{!d.heartbeats?.length&&<p>No n8n heartbeat is recorded yet. Import/activate the workflow bundle and configure its internal API secret.</p>}</div><div className="panel"><h3>Recorded workflow deployments</h3>{(d.deployments||[]).map((x:any)=><div className="list" key={x.id}><div><b>{x.workflow_name}</b><span>{x.workflow_key} · bundle {x.bundle_version} · n8n #{x.n8n_workflow_id}</span></div><Badge tone={x.active?"good":"neutral"}>{x.deployment_status}</Badge></div>)}{!d.deployments?.length&&<p>No deployment metadata recorded yet.</p>}</div><div className="two-col"><div className="panel"><h3>Outbox</h3>{(d.outbox||[]).map((x:any)=><div className="list" key={x.status}><div><b>{x.status}</b><span>oldest {date(x.oldest)}</span></div><strong>{fmt(x.count)}</strong></div>)}</div><div className="panel"><h3>Follow-ups</h3>{(d.followups||[]).map((x:any)=><div className="list" key={x.status}><div><b>{x.status}</b><span>oldest due {date(x.oldest_due)}</span></div><strong>{fmt(x.count)}</strong></div>)}</div></div><div className="panel"><h3>Worker heartbeats</h3>{(d.workers||[]).map((w:any)=><div className="list" key={w.worker_key}><div><b>{w.worker_key}</b><span>{(w.queues||[]).join(", ")}</span></div><Badge tone={Date.now()-new Date(w.last_seen_at).getTime()<60000?"good":"bad"}>{date(w.last_seen_at)}</Badge></div>)}</div></>}</>
}

function FeatureFlags(){
 const[rows,setRows]=useState<any[]>([]);const[key,setKey]=useState("");const[description,setDescription]=useState("");const load=()=>api<any>("/v1/admin/feature-flags").then(d=>setRows(d.flags||[]));useEffect(()=>{load()},[]);
 async function save(flag:any){await api(`/v1/admin/feature-flags/${encodeURIComponent(flag.key)}`,{method:"PUT",body:JSON.stringify({enabled:!flag.enabled,description:flag.description||null,rules:flag.rules||{}})});load()}
 async function create(e:FormEvent){e.preventDefault();await api(`/v1/admin/feature-flags/${encodeURIComponent(key)}`,{method:"PUT",body:JSON.stringify({enabled:false,description,rules:{}})});setKey("");setDescription("");load()}
 return <><div className="section-head"><div><h2>Feature flags</h2><p>Platform-owned release controls. Flags are explicit and audited.</p></div></div><form className="panel row" onSubmit={create}><input required placeholder="feature.key" value={key} onChange={e=>setKey(e.target.value)}/><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary">Create disabled flag</button></form><div className="table"><table><thead><tr><th>Flag</th><th>Description</th><th>State</th><th>Updated</th><th/></tr></thead><tbody>{rows.map(f=><tr key={f.key}><td><code>{f.key}</code></td><td>{f.description||"—"}</td><td><Badge tone={f.enabled?"good":"neutral"}>{f.enabled?"enabled":"disabled"}</Badge></td><td>{date(f.updated_at)}</td><td><button onClick={()=>save(f)}>{f.enabled?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div></>
}

function Health(){const[d,setD]=useState<any>(null);const load=()=>api<any>("/v1/admin/health").then(setD);useEffect(()=>{load()},[]);return <><div className="section-head"><div><h2>Infrastructure health</h2><p>Read-only application view of existing infrastructure dependencies.</p></div><button onClick={load}>Refresh checks</button></div><div className="health-grid">{d&&Object.entries(d.health||{}).map(([k,v]:any)=><div className="panel" key={k}><div className="row"><h3>{k}</h3><Badge tone={v.ok?"good":"bad"}>{v.ok?"available":"degraded"}</Badge></div><pre>{JSON.stringify(v,null,2)}</pre></div>)}</div></>}

function Audit(){const[rows,setRows]=useState<any[]>([]);const[action,setAction]=useState("");useEffect(()=>{api<any>(`/v1/admin/audit${qs({action})}`).then(d=>setRows(d.events||[]))},[action]);return <><div className="section-head"><div><h2>Audit trail</h2><p>Privileged and customer-sensitive changes are append-oriented and searchable.</p></div><input className="search" placeholder="Exact action filter" value={action} onChange={e=>setAction(e.target.value)}/></div><div className="table"><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>Tenant</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{date(a.created_at)}</td><td>{a.actor_email||a.actor_type}</td><td><code>{a.action}</code></td><td>{a.resource_type} · {a.resource_id||"—"}</td><td>{a.tenant_id||"platform"}</td></tr>)}</tbody></table></div></>}

function Plans(){const[rows,setRows]=useState<any[]>([]);const[open,setOpen]=useState(false);const[form,setForm]=useState({key:"",name:"",limits:'{"businesses":3,"channels":10,"messagesPerMonth":50000}'});const load=()=>api<any>("/v1/admin/plans").then(d=>setRows(d.plans||[]));useEffect(()=>{load()},[]);async function create(e:FormEvent){e.preventDefault();await api("/v1/admin/plans",{method:"POST",body:JSON.stringify({key:form.key,name:form.name,limits:JSON.parse(form.limits),features:{byok:true,training:true,customCollections:true}})});setOpen(false);load()}return <><div className="section-head"><div><h2>Plans & limits</h2><p>Data-driven entitlements are resolved with provider, global, plan, admin and customer limits.</p></div><button className="primary" onClick={()=>setOpen(true)}>+ Plan</button></div><div className="plan-grid">{rows.map(p=><div className="panel" key={p.id}><div className="row"><h3>{p.name}</h3><Badge tone={p.active?"good":"neutral"}>{p.key}</Badge></div><pre>{JSON.stringify(p.limits,null,2)}</pre></div>)}</div>{open&&<Modal title="Create plan" onClose={()=>setOpen(false)}><form onSubmit={create}><label>Key<input required value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Limits JSON<textarea rows={8} value={form.limits} onChange={e=>setForm({...form,limits:e.target.value})}/></label><button className="primary">Create plan</button></form></Modal>}</>}

function Security({me,reload}:{me:any;reload:()=>void}){const[status,setStatus]=useState<any>(null);const[setup,setSetup]=useState<any>(null);const[code,setCode]=useState("");const[recovery,setRecovery]=useState<string[]>([]);const load=()=>api<any>("/v1/admin/mfa/status").then(setStatus).catch(()=>{});useEffect(()=>{load()},[]);async function start(){setSetup(await api("/v1/admin/mfa/setup",{method:"POST",body:"{}"}))}async function confirm(){const r=await api<any>("/v1/admin/mfa/confirm",{method:"POST",body:JSON.stringify({code})});setRecovery(r.recoveryCodes||[]);setSetup(null);await load();await reload()}return <><div className="section-head"><div><h2>Super-admin security</h2><p>MFA is mandatory for privileged console access. Recovery codes are stored only as hashes.</p></div></div><div className="panel security-box"><div className="row"><div><h3>Authenticator MFA</h3><p>{status?.mfa_enabled?"Enabled for this administrator.":"Enrollment required before normal platform operations."}</p></div><Badge tone={status?.mfa_enabled?"good":"warn"}>{status?.mfa_enabled?"Enabled":"Setup required"}</Badge></div>{!status?.mfa_enabled&&<button className="primary" onClick={start}>Start MFA setup</button>}{status?.mfa_enabled&&<p><small>Recovery codes remaining: {status.recovery_codes_remaining ?? "—"}</small></p>}</div>{setup&&<Modal title="Enroll authenticator" onClose={()=>setSetup(null)}><p>Use this secret or the otpauth URI in your authenticator application.</p><code className="secret">{setup.secret}</code><textarea readOnly rows={3} value={setup.otpauthUri}/><label>6-digit code<input value={code} onChange={e=>setCode(e.target.value)}/></label><button className="primary" onClick={confirm}>Confirm and enable MFA</button></Modal>}{recovery.length>0&&<Modal title="Save recovery codes" onClose={()=>setRecovery([])}><div className="alert warn">Store these codes securely. They are shown only now.</div><div className="recovery">{recovery.map(c=><code key={c}>{c}</code>)}</div></Modal>}</>}
