"use client";

import Link from "next/link";
import { ChangeEvent, useCallback, useEffect, useMemo, useState } from "react";
import { API_URL, ApiClientError, api, qs } from "../../lib/api";

type Membership={tenant_id:string;tenant_name:string;role:string};
type Business={id:string;name:string};
type Asset={id:string;business_id?:string|null;original_name?:string|null;mime_type:string;kind?:string|null;size_bytes:number;visibility:"private"|"public";public_url?:string|null;reference_count?:number};
type MediaQuota={limits:{maxImageMegapixels:number;maxImageAssets:number;maxImageBytes:number;mediaStorageBytes:number};usage:{imageAssets:number;storageBytes:number};remaining:{imageAssets:number;storageBytes:number}};

const card={background:"#fff",border:"1px solid #e5e7eb",borderRadius:14,padding:18} as const;
const input={border:"1px solid #d1d5db",borderRadius:8,padding:"9px 11px",background:"#fff"} as const;
const button={border:0,borderRadius:8,padding:"10px 14px",fontWeight:750,cursor:"pointer"} as const;

async function validateImage(file:File,quota:MediaQuota|null){
  if(!file.type.startsWith("image/")||!quota)return;
  if(file.size>quota.limits.maxImageBytes)throw new Error(`Image must be ${(quota.limits.maxImageBytes/1024/1024).toFixed(0)} MB or smaller.`);
  if(quota.remaining.imageAssets<=0)throw new Error(`Image limit reached (${quota.limits.maxImageAssets} images). Delete an unused image or upgrade your package.`);
  try{const bitmap=await createImageBitmap(file);const mp=(bitmap.width*bitmap.height)/1_000_000;const size=`${bitmap.width}×${bitmap.height}`;bitmap.close();if(mp>quota.limits.maxImageMegapixels)throw new Error(`Image is ${mp.toFixed(2)} MP (${size}). Maximum allowed is ${quota.limits.maxImageMegapixels} MP.`)}catch(e){if(e instanceof Error&&/Maximum allowed|Image is/.test(e.message))throw e;/* Server performs authoritative format/dimension validation. */}
}

export default function MediaLibraryPage(){
  const[memberships,setMemberships]=useState<Membership[]>([]);const[tenantId,setTenantId]=useState("");const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState("");const[assets,setAssets]=useState<Asset[]>([]);const[storage,setStorage]=useState<any>(null);const[quota,setQuota]=useState<MediaQuota|null>(null);const[error,setError]=useState("");const[errorCode,setErrorCode]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{api<any>("/v1/auth/me").then(d=>{const rows=d?.memberships??[];setMemberships(rows);setTenantId(rows[0]?.tenant_id??"")}).catch(e=>setError(e instanceof Error?e.message:"Unable to load account."))},[]);
  useEffect(()=>{if(!tenantId)return;api<any>(`/v1/tenants/${tenantId}/businesses`).then(d=>{const rows=d.businesses??[];setBusinesses(rows);setBusinessId(v=>rows.some((b:Business)=>b.id===v)?v:(rows[0]?.id??""))}).catch(e=>setError(e instanceof Error?e.message:"Unable to load businesses."))},[tenantId]);
  const load=useCallback(async()=>{if(!tenantId)return;setError("");setErrorCode("");try{const[m,q]=await Promise.all([api<any>(`/v1/tenants/${tenantId}/media${qs({businessId})}`),api<MediaQuota>(`/v1/tenants/${tenantId}/media/limits`)]);setAssets(m.assets??[]);setQuota(q)}catch(e){setError(e instanceof Error?e.message:"Unable to load media.");return}try{const s=await api<any>(`/v1/tenants/${tenantId}/media/storage`);setStorage(s.storage??null)}catch(e){setStorage(null);setError(e instanceof Error?e.message:"Media storage is not configured.");setErrorCode(e instanceof ApiClientError?e.code:"")}},[tenantId,businessId]);
  useEffect(()=>{void load()},[load]);
  async function provision(){setBusy(true);setError("");setErrorCode("");try{await api(`/v1/tenants/${tenantId}/media/provision`,{method:"POST",body:"{}"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to provision media storage.");setErrorCode(e instanceof ApiClientError?e.code:"")}finally{setBusy(false)}}
  async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");try{await validateImage(file,quota);const fd=new FormData();fd.set("file",file);fd.set("visibility","private");await api(`/v1/tenants/${tenantId}/media`,{method:"POST",headers:businessId?{"x-business-id":businessId}:{},body:fd});await load()}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setBusy(false);e.target.value=""}}
  async function visibility(asset:Asset){setBusy(true);try{await api(`/v1/tenants/${tenantId}/media/${asset.id}/visibility`,{method:"PATCH",body:JSON.stringify({visibility:asset.visibility==="public"?"private":"public"})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to change visibility.")}finally{setBusy(false)}}
  async function remove(asset:Asset){if(!confirm(`Delete ${asset.original_name||"this file"}?`))return;setBusy(true);try{await api(`/v1/tenants/${tenantId}/media/${asset.id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}finally{setBusy(false)}}
  const used=Number(storage?.used_bytes??quota?.usage.storageBytes??0);const available=storage?.available_bytes==null?(quota?.remaining.storageBytes??null):Number(storage.available_bytes);
  const canProvision=useMemo(()=>errorCode==="MEDIA_NOT_CONFIGURED"||errorCode==="MEDIA_AUTO_PROVISION_DISABLED",[errorCode]);
  return <main style={{minHeight:"100vh",background:"#f6f8fc",fontFamily:"Inter,system-ui,sans-serif",padding:"32px 24px"}}><div style={{maxWidth:1250,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:18,marginBottom:22}}><div><div style={{fontSize:12,textTransform:"uppercase",letterSpacing:".12em",color:"#6b7280",fontWeight:800}}>Customer Panel</div><h1 style={{margin:"5px 0 6px",fontSize:30}}>Media library</h1><p style={{margin:0,color:"#667085",maxWidth:780}}>Upload reusable product/service images and private documents. Image count, megapixels and storage are limited by your package.</p></div><div style={{display:"flex",gap:12,alignItems:"center"}}><Link href="/catalogs" style={{color:"#4f46e5",fontWeight:750,textDecoration:"none"}}>Data / Catalogs</Link><Link href="/" style={{color:"#4f46e5",fontWeight:750,textDecoration:"none"}}>← Dashboard</Link></div></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:18}}><label style={{display:"grid",gap:6,color:"#667085",fontSize:13}}>Workspace<select style={input} value={tenantId} onChange={e=>setTenantId(e.target.value)}>{memberships.map(m=><option key={m.tenant_id} value={m.tenant_id}>{m.tenant_name} · {m.role}</option>)}</select></label><label style={{display:"grid",gap:6,color:"#667085",fontSize:13}}>Business<select style={input} value={businessId} onChange={e=>setBusinessId(e.target.value)}><option value="">All businesses</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div>
    {error&&<div style={{...card,borderColor:"#fecaca",background:"#fff7f6",marginBottom:16,color:"#b42318"}}><strong>{error}</strong>{canProvision&&<div style={{display:"flex",alignItems:"center",gap:12,marginTop:10,flexWrap:"wrap"}}><button disabled={busy} onClick={()=>void provision()} style={{...button,background:"#4f46e5",color:"#fff"}}>{busy?"Setting up…":"Set up media storage"}</button></div>}</div>}
    {(storage||quota)&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12,marginBottom:18}}><div style={card}><div style={{color:"#667085",fontSize:13}}>Used storage</div><div style={{fontSize:26,fontWeight:800,marginTop:5}}>{(used/1024/1024).toFixed(1)} MB</div><div style={{fontSize:12,color:"#667085",marginTop:4}}>Package cap {quota?`${(quota.limits.mediaStorageBytes/1024/1024).toFixed(0)} MB`:"—"}</div></div><div style={card}><div style={{color:"#667085",fontSize:13}}>Images</div><div style={{fontSize:26,fontWeight:800,marginTop:5}}>{quota?`${quota.usage.imageAssets} / ${quota.limits.maxImageAssets}`:"—"}</div><div style={{fontSize:12,color:"#667085",marginTop:4}}>{quota?`${quota.remaining.imageAssets} remaining`:""}</div></div><div style={card}><div style={{color:"#667085",fontSize:13}}>Per image</div><div style={{fontSize:26,fontWeight:800,marginTop:5}}>{quota?`${quota.limits.maxImageMegapixels} MP`:"—"}</div><div style={{fontSize:12,color:"#667085",marginTop:4}}>Up to {quota?(quota.limits.maxImageBytes/1024/1024).toFixed(0):"—"} MB encoded</div></div><div style={{...card,display:"flex",alignItems:"center",justifyContent:"center"}}><label style={{...button,background:"#4f46e5",color:"#fff",display:"inline-flex",cursor:busy?"wait":"pointer"}}>{busy?"Working…":"+ Upload private file"}<input type="file" disabled={busy} onChange={upload} style={{display:"none"}}/></label></div></div>}
    <section style={card}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><h2 style={{margin:0,fontSize:20}}>Files</h2><div style={{color:"#667085",fontSize:13,marginTop:4}}>{assets.length} media asset(s){businessId?" in selected business":""}</div></div>{storage&&<label style={{...button,background:"#4f46e5",color:"#fff",display:"inline-flex"}}>+ Upload<input type="file" disabled={busy} onChange={upload} style={{display:"none"}}/></label>}</div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:14}}>{assets.map(a=><article key={a.id} style={{border:"1px solid #e5e7eb",borderRadius:12,overflow:"hidden",background:"#fff"}}><div style={{height:155,background:"#f3f4f6",display:"grid",placeItems:"center",overflow:"hidden"}}>{a.mime_type?.startsWith("image/")?<img src={a.public_url||`${API_URL}/v1/tenants/${tenantId}/media/${a.id}/content`} alt={a.original_name||"media"} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<strong style={{color:"#667085"}}>{(a.kind||"FILE").toUpperCase()}</strong>}</div><div style={{padding:13}}><strong style={{display:"block",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{a.original_name||a.id}</strong><div style={{fontSize:12,color:"#667085",marginTop:5}}>{(Number(a.size_bytes||0)/1024).toFixed(1)} KB · {a.visibility} · {a.reference_count??0} ref</div><div style={{display:"flex",gap:8,marginTop:12}}><button disabled={busy} onClick={()=>void visibility(a)} style={{...button,padding:"7px 10px",background:"#eef2ff",color:"#4338ca"}}>{a.visibility==="public"?"Make private":"Publish"}</button>{Number(a.reference_count??0)===0&&<button disabled={busy} onClick={()=>void remove(a)} style={{...button,padding:"7px 10px",background:"#fff1f2",color:"#be123c"}}>Delete</button>}</div></div></article>)}</div>{!assets.length&&<div style={{padding:"46px 16px",textAlign:"center",color:"#667085"}}>No media uploaded yet.</div>}</section>
  </div></main>;
}
