"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api } from "../../lib/api";
import AdminAccessGuard from "../../components/AdminAccessGuard";

type Provider={id:string;name:string;provider:string;key_hint?:string|null;base_url?:string|null;status:string};
type ModelRoute={id:string;provider_connection_id:string;provider_name:string;provider:string;task_key:string;model:string;priority:number;active:boolean;input_credits_per_1k_tokens:number|string;output_credits_per_1k_tokens:number|string;request_credits:number|string};
type CatalogModel={id:string;label:string};
type Plan={id:string;key:string;name:string;active:boolean;limits:any;features:any};
const tasks=["DEFAULT_CHAT","IMAGE_ANALYSIS","AUDIO_TRANSCRIPTION","PROMPT_SYNTHESIS","EMBEDDINGS","STRUCTURED_EXTRACTION","INTENT_CLASSIFICATION"] as const;

const box={border:"1px solid #e5e7eb",borderRadius:14,padding:20,background:"white"} as const;
const inputStyle={padding:10,borderRadius:8,border:"1px solid #d1d5db",width:"100%"} as const;

export default function PlatformAiPage(){
  const[providers,setProviders]=useState<Provider[]>([]);const[models,setModels]=useState<ModelRoute[]>([]);const[plans,setPlans]=useState<Plan[]>([]);const[catalog,setCatalog]=useState<CatalogModel[]>([]);const[error,setError]=useState("");const[notice,setNotice]=useState("");
  const[providerForm,setProviderForm]=useState({name:"",provider:"openai",apiKey:"",baseUrl:""});
  const[modelForm,setModelForm]=useState({providerConnectionId:"",taskKey:"DEFAULT_CHAT",model:"",priority:100,inputCreditsPer1kTokens:1,outputCreditsPer1kTokens:1,requestCredits:0});
  const[planDrafts,setPlanDrafts]=useState<Record<string,{monthlyAiTokens:number;monthlyAiCredits:number}>>({});
  const load=useCallback(async()=>{setError("");const[p,m,pl]=await Promise.all([api<any>("/v1/admin/platform-ai/providers"),api<any>("/v1/admin/platform-ai/models"),api<any>("/v1/admin/plans")]);setProviders(p.providers??[]);setModels(m.models??[]);const planRows:Plan[]=pl.plans??[];setPlans(planRows);setPlanDrafts(Object.fromEntries(planRows.map(x=>[x.id,{monthlyAiTokens:Number(x.limits?.monthlyAiTokens??0),monthlyAiCredits:Number(x.limits?.monthlyAiCredits??0)}])));setModelForm(current=>({...current,providerConnectionId:current.providerConnectionId||p.providers?.[0]?.id||""}));},[]);
  useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Unable to load platform AI settings."));},[load]);
  const selectedProvider=useMemo(()=>providers.find(p=>p.id===modelForm.providerConnectionId),[providers,modelForm.providerConnectionId]);
  async function addProvider(e:FormEvent){e.preventDefault();setError("");setNotice("");try{await api("/v1/admin/platform-ai/providers",{method:"POST",body:JSON.stringify({...providerForm,baseUrl:providerForm.baseUrl||undefined})});setProviderForm({name:"",provider:"openai",apiKey:"",baseUrl:""});setNotice("Platform AI provider saved.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save provider.");}}
  async function loadCatalog(){if(!modelForm.providerConnectionId)return;setError("");try{const data=await api<any>(`/v1/admin/platform-ai/providers/${modelForm.providerConnectionId}/catalog`);setCatalog(data.models??[]);}catch(e){setCatalog([]);setError(e instanceof Error?e.message:"Unable to load provider models.");}}
  useEffect(()=>{setCatalog([]);setModelForm(x=>({...x,model:""}));if(modelForm.providerConnectionId)void loadCatalog();},[modelForm.providerConnectionId]);
  async function addModel(e:FormEvent){e.preventDefault();setError("");setNotice("");try{await api("/v1/admin/platform-ai/models",{method:"POST",body:JSON.stringify({...modelForm,parameters:{},active:true})});setNotice(`${modelForm.taskKey} platform route saved.`);setModelForm(x=>({...x,model:""}));await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save platform model route.");}}
  async function toggleModel(row:ModelRoute){await api(`/v1/admin/platform-ai/models/${row.id}`,{method:"PATCH",body:JSON.stringify({active:!row.active})});await load();}
  async function savePlan(plan:Plan){const draft=planDrafts[plan.id];if(!draft)return;setError("");setNotice("");try{await api(`/v1/admin/plans/${plan.id}/ai-allowance`,{method:"PATCH",body:JSON.stringify(draft)});setNotice(`${plan.name} AI allowance updated.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update plan allowance.");}}
  return <AdminAccessGuard><main style={{maxWidth:1280,margin:"0 auto",padding:"36px 24px",fontFamily:"Inter,system-ui,sans-serif",background:"#f8fafc",minHeight:"100vh"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",marginBottom:24}}><div><div style={{fontSize:13,color:"#6b7280",fontWeight:800,textTransform:"uppercase",letterSpacing:".08em"}}>Super Admin</div><h1 style={{margin:"6px 0"}}>Platform AI</h1><p style={{color:"#6b7280",margin:0}}>Configure provider credentials, platform task models and monthly Free/Pro token-credit allowances. Customers cannot supply their own AI keys or model routes.</p></div><Link href="/" style={{color:"#4f46e5",fontWeight:700,textDecoration:"none"}}>← Admin dashboard</Link></div>
    {error&&<div style={{padding:12,borderRadius:8,background:"#fef2f2",color:"#991b1b",marginBottom:16}}>{error}</div>}{notice&&<div style={{padding:12,borderRadius:8,background:"#ecfdf5",color:"#065f46",marginBottom:16}}>{notice}</div>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(360px,1fr))",gap:18,marginBottom:18}}>
      <section style={box}><h2 style={{marginTop:0}}>Platform provider</h2><form onSubmit={addProvider} style={{display:"grid",gap:12}}><label>Name<input required style={inputStyle} value={providerForm.name} onChange={e=>setProviderForm({...providerForm,name:e.target.value})}/></label><label>Provider<select style={inputStyle} value={providerForm.provider} onChange={e=>setProviderForm({...providerForm,provider:e.target.value})}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option><option value="openai_compatible">OpenAI-compatible</option></select></label><label>API key<input required type="password" autoComplete="off" style={inputStyle} value={providerForm.apiKey} onChange={e=>setProviderForm({...providerForm,apiKey:e.target.value})}/></label>{providerForm.provider==="openai_compatible"&&<label>Base URL<input required style={inputStyle} value={providerForm.baseUrl} onChange={e=>setProviderForm({...providerForm,baseUrl:e.target.value})}/></label>}<button style={{padding:"11px 16px",border:0,borderRadius:8,background:"#4f46e5",color:"white",fontWeight:800}}>Save platform provider</button></form><div style={{marginTop:16,display:"grid",gap:8}}>{providers.map(p=><div key={p.id} style={{padding:10,border:"1px solid #e5e7eb",borderRadius:8}}><b>{p.name}</b> · {p.provider}<div style={{fontSize:12,color:"#6b7280"}}>{p.status} · {p.key_hint||"key hidden"}</div></div>)}</div></section>
      <section style={box}><h2 style={{marginTop:0}}>Task model route</h2><form onSubmit={addModel} style={{display:"grid",gap:12}}><label>Provider<select required style={inputStyle} value={modelForm.providerConnectionId} onChange={e=>setModelForm({...modelForm,providerConnectionId:e.target.value})}><option value="">Select…</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name} · {p.provider}</option>)}</select></label><label>Task<select style={inputStyle} value={modelForm.taskKey} onChange={e=>setModelForm({...modelForm,taskKey:e.target.value})}>{tasks.map(t=><option key={t}>{t}</option>)}</select></label><label>Model ID<input required list="platform-model-catalog" style={inputStyle} placeholder="Select or type provider model ID" value={modelForm.model} onChange={e=>setModelForm({...modelForm,model:e.target.value})}/><datalist id="platform-model-catalog">{catalog.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</datalist></label><div style={{fontSize:12,color:"#6b7280"}}>{selectedProvider?`${selectedProvider.provider} · ${catalog.length} model(s) discovered`:"Select a provider"}</div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:10}}><label>Priority<input type="number" style={inputStyle} value={modelForm.priority} onChange={e=>setModelForm({...modelForm,priority:Number(e.target.value)})}/></label><label>Request credits<input type="number" step="0.001" min="0" style={inputStyle} value={modelForm.requestCredits} onChange={e=>setModelForm({...modelForm,requestCredits:Number(e.target.value)})}/></label><label>Input credits / 1K<input type="number" step="0.001" min="0" style={inputStyle} value={modelForm.inputCreditsPer1kTokens} onChange={e=>setModelForm({...modelForm,inputCreditsPer1kTokens:Number(e.target.value)})}/></label><label>Output credits / 1K<input type="number" step="0.001" min="0" style={inputStyle} value={modelForm.outputCreditsPer1kTokens} onChange={e=>setModelForm({...modelForm,outputCreditsPer1kTokens:Number(e.target.value)})}/></label></div><button style={{padding:"11px 16px",border:0,borderRadius:8,background:"#4f46e5",color:"white",fontWeight:800}}>Save task route</button></form></section>
    </div>
    <section style={{...box,marginBottom:18}}><h2 style={{marginTop:0}}>Active platform routes</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:9}}>Task</th><th style={{textAlign:"left",padding:9}}>Provider</th><th style={{textAlign:"left",padding:9}}>Model</th><th style={{textAlign:"left",padding:9}}>Priority</th><th style={{textAlign:"left",padding:9}}>Credits</th><th/></tr></thead><tbody>{models.map(r=><tr key={r.id} style={{borderTop:"1px solid #e5e7eb"}}><td style={{padding:9}}>{r.task_key}</td><td style={{padding:9}}>{r.provider_name} · {r.provider}</td><td style={{padding:9}}><code>{r.model}</code></td><td style={{padding:9}}>{r.priority}</td><td style={{padding:9,fontSize:12}}>req {Number(r.request_credits)} · in {Number(r.input_credits_per_1k_tokens)}/1K · out {Number(r.output_credits_per_1k_tokens)}/1K</td><td style={{padding:9}}><button onClick={()=>void toggleModel(r)} style={{padding:"7px 10px",borderRadius:7,border:"1px solid #d1d5db",background:"white"}}>{r.active?"Disable":"Enable"}</button></td></tr>)}</tbody></table>{!models.length&&<p style={{color:"#6b7280"}}>No platform model routes yet.</p>}</div></section>
    <section style={box}><h2 style={{marginTop:0}}>Monthly package allowances</h2><p style={{color:"#6b7280"}}>No payment checkout is enabled. Assign plans to tenants manually from the existing tenant administration flow. These limits reset monthly.</p><div style={{display:"grid",gap:12}}>{plans.map(plan=>{const draft=planDrafts[plan.id]??{monthlyAiTokens:0,monthlyAiCredits:0};return <div key={plan.id} style={{display:"grid",gridTemplateColumns:"minmax(160px,1fr) 1fr 1fr auto",gap:12,alignItems:"end",padding:14,border:"1px solid #e5e7eb",borderRadius:10}}><div><b>{plan.name}</b><div style={{fontSize:12,color:"#6b7280"}}>{plan.key} · {plan.active?"active":"inactive"}</div></div><label>Tokens / month<input type="number" min="0" style={inputStyle} value={draft.monthlyAiTokens} onChange={e=>setPlanDrafts({...planDrafts,[plan.id]:{...draft,monthlyAiTokens:Number(e.target.value)}})}/></label><label>Credits / month<input type="number" step="0.001" min="0" style={inputStyle} value={draft.monthlyAiCredits} onChange={e=>setPlanDrafts({...planDrafts,[plan.id]:{...draft,monthlyAiCredits:Number(e.target.value)}})}/></label><button onClick={()=>void savePlan(plan)} style={{padding:"10px 14px",border:0,borderRadius:8,background:"#111827",color:"white",fontWeight:700}}>Save</button></div>})}</div></section>
  </main></AdminAccessGuard>;
}
