"use client";
import {FormEvent,useEffect,useState} from "react";
import Link from "next/link";
import {api,setCsrfToken} from "../../lib/api";

export default function AcceptInvitePage(){
 const[token,setToken]=useState("");const[invite,setInvite]=useState<any>(null);const[me,setMe]=useState<any>(null);const[form,setForm]=useState({name:"",password:""});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState(false);
 useEffect(()=>{const t=new URLSearchParams(window.location.search).get("token")||"";setToken(t);if(!t){setError("Invitation token is missing.");return;}Promise.all([api<any>(`/v1/invitations/${encodeURIComponent(t)}`),api<any>("/v1/auth/me").catch(()=>null)]).then(([i,m])=>{setInvite(i.invitation);setMe(m)}).catch(e=>setError(e instanceof Error?e.message:"Invitation could not be loaded."));},[]);
 async function acceptExisting(){setBusy(true);setError("");try{await api(`/v1/invitations/${encodeURIComponent(token)}/accept`,{method:"POST",body:"{}"});setDone(true);}catch(e){setError(e instanceof Error?e.message:"Could not accept invitation.");}finally{setBusy(false)}}
 async function signup(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const result=await api<any>(`/v1/invitations/${encodeURIComponent(token)}/signup`,{method:"POST",body:JSON.stringify(form)});if(result.csrfToken)setCsrfToken(result.csrfToken);setDone(true);}catch(e){setError(e instanceof Error?e.message:"Could not create account.");}finally{setBusy(false)}}
 if(done)return <main className="auth-shell"><section className="auth-card"><h1>Invitation accepted</h1><div className="alert success">You now have access to {invite?.tenantName||"the workspace"}.</div><Link className="button primary" href="/">Open workspace</Link></section></main>;
 return <main className="auth-shell"><section className="auth-card"><h1>Join workspace</h1>{invite&&<div className="result-box"><b>{invite.tenantName}</b><p>{invite.email} · {invite.role}</p><small>Expires {new Date(invite.expiresAt).toLocaleString()}</small></div>}{error&&<div className="alert error">{error}</div>}{invite&&(me?.principal?<div className="stack"><p>Signed in as <b>{me.principal.email}</b>.</p><button className="button primary" disabled={busy||me.principal.email?.toLowerCase()!==invite.email?.toLowerCase()} onClick={acceptExisting}>Accept invitation</button>{me.principal.email?.toLowerCase()!==invite.email?.toLowerCase()&&<p className="muted">Sign out and use the email address that received this invitation.</p>}<Link className="link-button" href="/">Back to workspace</Link></div>:<form className="stack" onSubmit={signup}><p>Create an account for <b>{invite.email}</b> and join this workspace.</p><label className="field"><span>Your name</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Password</span><input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="button primary" disabled={busy}>{busy?"Joining…":"Create account & join"}</button><p className="muted">Already have an account? Sign in from the Customer Panel using {invite.email}, then reopen this invitation link.</p><Link className="link-button" href="/">Go to sign in</Link></form>)}</section></main>
}
